---
version: '2'
services:
    app:
        build: .
        environment:
            REALM: prod
            REDIS_URL: "//redis:6379"
        ports:
            - "8000:8000"

    redis:
        image: redis
